local c = require("gruvboy.colors")

local theme = {
	Comment = { bg = c.bg0, fg = c.bg4, italic = true },
	ColorColumn = { bg = c.bg0, fg = c.bg1 },
	Conceal = { fg = c.bright_blue },
	Cursor = { reverse = true },
	lCursor = { reverse = true },
	CursorIM = { reverse = true },
	CursorColumn = { bg = c.bg1 },
	CursorLine = { bg = c.bg1 },
	Directory = { fg = c.bright_green, bold = true },
	DiffAdd = { fg = c.bright_green },
	DiffChange = { fg = c.bright_aqua, reverse = true },
	DiffDelete = { fg = c.bright_red, reverse = true },
	DiffText = { fg = c.bright_yellow, reverse = true },
	EndOfBuffer = { fg = c.bg2 },
	TermCursor = { reverse = true },
	TermCursorNC = { fg = c.bg1, bg = c.fg1 },
	ErrorMsg = { fg = c.bg0, bg = c.bright_red },
	VertSplit = { bg = c.bg0, fg = c.bg2 },
	Folded = { fg = c.bg4, bg = c.bg1, italic = true },
	FoldColumn = { fg = c.bg4, bg = c.bg1 },
	SignColumn = { fg = c.fg1 },
	IncSearch = { fg = c.bright_yellow, reverse = true },
	Substitute = { fg = c.bright_yellow, reverse = true },
	LineNr = { fg = c.gray },
	CursorLineNr = { fg = c.yellow },
	MatchParen = { bg = c.bg2, underline=true },
	ModeMsg = { fg = c.fg1 },
	MsgArea = { fg = c.fg1 },
	MsgSeparator = { fg = c.fg1 },
	MoreMsg = { fg = c.yellow },
	NonText = { fg = c.bg2 },
	Normal = { fg = c.fg1, bg = c.bg0 },
	NormalFloat = { fg = c.fg1, bg = c.bg0 },
	NormalNC = { fg = c.fg1 },
	Pmenu = { fg = c.fg1, bg = c.bg2 },
	PmenuSel = { fg = c.bg2, bg = c.bright_blue, bold=true },
	PmenuSbar = { bg = c.bg2 },
	PmenuThumb = { bg = c.bg3 },
	Question = { fg = c.bright_orange, bold=true },
	QuickFixLine = { fg = c.bright_yellow, reverse = true },
	Search = { fg = c.bright_yellow, reverse = true },
	SpecialKey = { fg = c.bg4 },
	SpellBad = { fg = c.fg0, underline=true, sp = c.red },
	SpellCap = { fg = c.fg0, underline=true, sp = c.yellow },
	SpellLocal = { fg = c.fg0, underline=true, sp = c.green },
	SpellRare = { fg = c.fg0, underline=true, sp = c.blue },
	StatusLine = { bg = c.bg0, fg = c.none },
	StatusLineNC = { bg = c.none, fg = c.none },
	TabLine = { bg = c.bg1, fg = c.fg0 },
	TabLineFill = { fg = c.fg0 },
	TabLineSel = { bg = c.bg1, fg = c.yellow },
	Title = { fg = c.aqua, bold=true },
	Visual = { bg = c.bg3 },
	VisualNOS = { reverse = true },
	WarningMsg = { fg = c.red },
	Whitespace = { bg = c.bg0, fg = c.bg4, italic = true },
	WildMenu = { fg = c.bright_blue, bg = c.bg2, bold=true },

	Constant = { fg = c.purple },
	String = { fg = c.green },
	Character = { fg = c.purple },
	Number = { fg = c.purple },
	Boolean = { fg = c.purple },
	Float = { fg = c.purple },

	Identifier = { fg = c.blue },
	Function = { fg = c.green, bold=true },

	Statement = { fg = c.red },
	Conditional = { fg = c.red },
	Repeat = { fg = c.red },
	Label = { fg = c.red },
	Operator = { fg = c.aqua },
	Keyword = { fg = c.red },
	Exception = { fg = c.red },

	PreProc = { fg = c.aqua },
	Include = { fg = c.aqua },
	Define = { fg = c.aqua },
	Macro = { fg = c.aqua },
	PreCondit = { fg = c.aqua },

	Type = { fg = c.yellow },
	StorageClass = { fg = c.orange },
	Structure = { fg = c.aqua },
	Typedef = { fg = c.yellow },

	Special = { fg = c.orange },
	SpecialChar = { fg = c.purple },
	Tag = { fg = c.red },
	Delimiter = { fg = c.orange },
	SpecialComment = { fg = c.red },
	Debug = { fg = c.red },

	Underlined = { underline=true },
	Bold = { bold=true },
	Italic = { italic = true },

	Ignore = { fg = c.fg0 },
	Error = { fg = c.bright_red, bold = true, italic = true, reverse = true },
	Todo = { fg = c.fg3, bold = true, italic = true, reverse = true },

	FloatBorder = { fg = c.bg4, bg = c.bg0 },
}

return theme

-- vi:nowrap
