local c = require("gruvboy.colors")

local M = {
	--
	--See :h highlight-groups
	ColorColumn = { fg = c.light0 },
	Conceal = { fg = c.light1 },
	CurSearch = { bg = c.light0, fg = c.dark0 },
	Cursor = { bg = c.light0, fg = c.dark0 },
	ICursor = { link = "Cursor" },
	CursorIM = { link = "Cursor" },
	CursorColumn = { bg = c.dark1 },
	CursorLine = { link = "CursorColumn" },
	Directory = { fg = c.green, bold = true },
	DiffAdd = { fg = c.green },
	DiffChange = { fg = c.aqua },
	DiffDelete = { fg = c.red },
	DiffText = { fg = c.yellow },
	EndOfBuffer = { link = "ColorColumn" },
	TermCursor = { link = "Cursor" },
	TermCursorNC = { link = "TermCursor" },
	ErrorMsg = { bg = c.red, fg = c.dark0 },
	WinSeparator = { fg = c.light0 },
	Folded = { fg = c.dark1 },
	FoldedColumn = { link = "Folded" },
	SignColumn = { fg = c.dark3 },
	IncSearch = { link = "CurSearch" },
	Substitute = { link = "IncSearch" },
	LineNr = { link = "SignColumn" },
	LineNrAbove = { link = "SignColumn" },
	LineNrBelow = { link = "SignColumn" },
	CursorLineNr = { link = "CursorLine" },
	CursorLineFold = { link = "SignColumn" },
	CursorLineSign = { link = "SignColumn" },
	MatchParen = { bg = c.light1, underline = true },
	ModeMsg = { fg = c.light0 },
	MsgArea = { fg = c.light0 },
	MsgSeparator = { fg = c.light1 },
	MoreMsg = { fg = c.light1 },
	NonText = { fg = c.light1 },
	Normal = { bg = c.dark0, fg = c.light0 },
	NormalFloat = { link = "Normal" },
	FloatBorder = { fg = c.light0 },
	FloatTitle = { fg = c.light0, bold = true },
	NormalNC = { link = "Normal" },
	Pmenu = { bg = c.dark0 },
	PmenuSel = { bg = c.light0, fg = c.dark0 },
	PmenuKind = { link = "Pmenu" },
	PmenuKindSel = { link = "PmenuSel" },
	PmenuExtra = { link = "Pmenu" },
	PmenuExtraSel = { link = "PmenuSel" },
	PmenuSbar = { link = "Normal" },
	PmenuThumb = { link = "PmenuSel" },
	Question = { link = "Normal" },
	QuickFixLine = { fg = c.yellow, reverse = true },
	Search = { link = "IncSearch" },
	SpecialKey = { fg = c.purple },
	SpellBad = { fg = c.light0, undercurl = true, bold = true },
	SpellCap = { link = "SpellBad" },
	SpellLocal = { link = "SpellBad" },
	SpellRare = { link = "SpellBad" },
	StatusLine = { bg = c.light0, fg = c.dark0 },
	StatusLineNC = { bg = "NONE" },
	TabLine = { bg = c.dark0, fg = c.light0 },
	TabLineFill = { link = "TabLine" },
	TabLineSel = { bg = c.dark1 },
	Title = { bold = true },
	Visual = { bg = c.light1, fg = c.dark0 },
	VisualNOS = { bg = c.dark1 },
	WarningMsg = { fg = c.yellow },
	Whitespace = { fg = c.dark1 },
	WildMenu = { bg = c.dark1, fg = c.light0 },
	WinBar = { bg = c.dark0, fg = c.light0 },
	WinBarNC = { link = "WinBar" },
	--
	--See :h group-name
	Comment = { fg = c.gray },
	Constant = { fg = c.purple },
	String = { fg = c.green },
	Character = { fg = c.purple },
	Number = { fg = c.purple },
	Boolean = { fg = c.purple },
	Float = { fg = c.purple },
	Identifier = { fg = c.blue },
	Function = { fg = c.green, bold = true },
	Statement = { fg = c.red },
	Conditional = { fg = c.red },
	Repeat = { fg = c.red },
	Label = { fg = c.red },
	Operator = { fg = c.green },
	Keyword = { fg = c.red },
	Exception = { fg = c.purple },
	PreProc = { fg = c.green },
	Include = { fg = c.green },
	Define = { fg = c.green },
	Macro = { fg = c.green },
	PreCondit = { fg = c.green },
	Type = { fg = c.yellow },
	StorageClass = { fg = c.orange },
	Structure = { fg = c.aqua },
	TypeDef = { fg = c.yellow },
	Special = { fg = c.orange },
	SpecialChar = { fg = c.purple },
	Tag = { fg = c.red },
	SpecialComment = { fg = c.red },
	Debug = { fg = c.red },
	Underline = { underline = true },
	Error = { fg = c.red, undercurl = true },
	Todo = { fg = c.dark0, bg = c.light0 },
	--
	--See :h lsp-highlight
	--LspReferenceText={},
	--LspReferenceRead={},
	--LspReferenceWrite={},
	--
	--See :h diagnostic-highlights
	DiagnosticError = { fg = c.red, undercurl = true },
	DiagnosticWarn = { fg = c.yellow, underline = true },
	DiagnosticInfo = { fg = c.blue, underline = true },
	DiagnosticHint = { fg = c.aqua, underline = true },
	DiagnosticSignError = { fg = c.red },
	DiagnosticSignWarn = { fg = c.yellow },
	DiagnosticSignInfo = { fg = c.blue },
	DiagnosticSignHint = { fg = c.aqua },
	DiagnosticVirtualTextError = { fg = c.red },
	DiagnosticVirtualTextWarn = { fg = c.yellow },
	DiagnosticVirtualTextInfo = { fg = c.blue },
	DiagnosticVirtualTextHint = { fg = c.aqua },
	--
	--See :h treesitter-highlight-groups
	["@text.literal"] = { link = "Comment" },
	["@text.reference"] = { link = "Identifier" },
	["@text.title"] = { link = "Title" },
	["@text.uri"] = { link = "Underlined" },
	["@text.underline"] = { link = "Underlined" },
	["@text.todo"] = { link = "Todo" },
	["@comment"] = { link = "Comment" },
	["@punctuation"] = { link = "Delimiter" },
	["@constant"] = { link = "Constant" },
	["@constant.builtin"] = { link = "Special" },
	["@constant.macro"] = { link = "Define" },
	["@define"] = { link = "Define" },
	["@macro"] = { link = "Macro" },
	["@string"] = { link = "String" },
	["@string.escape"] = { link = "SpecialChar" },
	["@string.special"] = { link = "SpecialChar" },
	["@character"] = { link = "Character" },
	["@character.special"] = { link = "SpecialChar" },
	["@number"] = { link = "Number" },
	["@boolean"] = { link = "Boolean" },
	["@float"] = { link = "Float" },
	["@function"] = { link = "Function" },
	["@function.builtin"] = { link = "Special" },
	["@function.macro"] = { link = "Macro" },
	["@parameter"] = { link = "Identifier" },
	["@method"] = { link = "Function" },
	["@field"] = { link = "Identifier" },
	["@property"] = { link = "Identifier" },
	["@constructor"] = { link = "Special" },
	["@conditional"] = { link = "Conditional" },
	["@repeat"] = { link = "Repeat" },
	["@label"] = { link = "Label" },
	["@operator"] = { link = "Operator" },
	["@keyword"] = { link = "Keyword" },
	["@exception"] = { link = "Exception" },
	["@variable"] = { fg = c.light0 },
	["@type"] = { link = "Type" },
	["@type.definition"] = { link = "Typedef" },
	["@storageclass"] = { link = "StorageClass" },
	["@structure"] = { link = "Structure" },
	["@namespace"] = { link = "Identifier" },
	["@include"] = { link = "Include" },
	["@preproc"] = { link = "PreProc" },
	["@debug"] = { link = "Debug" },
	["@tag"] = { link = "Tag" },
	--
	--See :h lsp-semantic-highlight
	["@lsp.type.class"] = { link = "Structure" },
	["@lsp.type.decorator"] = { link = "Function" },
	["@lsp.type.enum"] = { link = "Structure" },
	["@lsp.type.enumMember"] = { link = "Constant" },
	["@lsp.type.function"] = { link = "Function" },
	["@lsp.type.interface"] = { link = "Structure" },
	["@lsp.type.macro"] = { link = "Macro" },
	["@lsp.type.method"] = { link = "Function" },
	["@lsp.type.namespace"] = { link = "Structure" },
	["@lsp.type.parameter"] = { link = "Identifier" },
	["@lsp.type.property"] = { link = "Identifier" },
	["@lsp.type.struct"] = { link = "Structure" },
	["@lsp.type.type"] = { link = "Type" },
	["@lsp.type.typeParameter"] = { link = "TypeDef" },
	["@lsp.type.variable"] = { link = "@Variable" },
	--
	--See :h cmp-highlight
	CmpItemAbbr = { bg = c.dark0, fg = c.light0 },
	CmpItemAbbrDeprecated = { bg = c.dark0, fg = c.light3 },
	CmpDocumentation = { link = "NormalFloat" },
	CmpDocumentationBorder = { link = "FloatBorder" },
	--
	--See :h gitsigns-highlight-groups
	GitSignAdd = { link = "DiffAdd" },
	GitSignChange = { link = "DiffChange" },
	GitSignDelete = { link = "DiffDelete" },
	--
	--See telescope.nvim/plugin/telescope.lua
	TelescopeSelection = { bg = c.light0, fg = c.dark0 },
	TelescopeSelectionCaret = { bg = c.light0, fg = c.dark0 },
	TelescopeMultiSelection = { fg = c.light0, bold = true },
	TelescopeNormal = { link = "NormalFloat" },
	TelescopeBorder = { link = "FloatBorder" },
	TelescopePreviewBorder = { link = "FloatBorder" },
	TelescopePromptBorder = { link = "FloatBorder" },
	TelescopeResultsBorder = { link = "FloatBorder" },
	TelescopePromptPrefix = { fg = c.light0 },
	TelescopeMatching = { bg = "NONE", fg = "NONE" },
	--
	--See :h translator-highlight
	TranslatorBorder = { link = "FloatBorder" },
	--
	--See :h neo-tree-highlight
	NeoTreeTabInactive = { bg = c.dark0, fg = c.dark3, bold = true },
	NeoTreeTabActive = { bg = c.dark0, fg = c.light0, bold = true },
	NeoTreeTabSeparatorActive = { bg = c.dark0, fg = c.dark0 },
	NeoTreeTabSeparatorInactive = { link = "NeoTreeTabSeparatorActive" },
}
return M
