local c = require("gruvboy.colors")
local base = require("gruvboy.base")

local theme = {
	TSAnnotation = { fg = c.blue },
	TSAttribute = { fg = c.aqua },
	TSBoolean = base.Boolean,
	TSCharacter = base.Character,
	TSComment = base.Comment,
	TSConstructor = { fg = c.orange },
	TSConditional = base.Conditional,
	TSConstant = base.Constant,
	TSConstBuiltin = { fg = c.purple },
	TSConstMacro = base.Macro,
	TSError = base.Error,
	TSException = base.Exception,
	TSField = { fg = c.blue },
	TSFloat = base.Float,
	TSFunction = base.Function,
	TSFuncBuiltin = { fg = c.aqua },
	TSFuncMacro = base.Macro,
	TSInclude = base.Include,
	TSKeyword = base.Keyword,
	TSKeywordFunction = base.Keyword,
	TSLabel = base.Label,
	TSMethod = { fg = c.aqua },
	TSNamespace = { fg = c.gray },
	TSNone = { fg = c.bg4 },
	TSNumber = base.Number,
	TSOperator = base.Operator,
	TSParameter = { fg = c.blue },
	TSParameterReference = { fg = c.blue },
	TSProperty = { fg = c.blue },
	TSPunctDelimiter = base.Delimiter,
	TSPunctBracket = { fg = c.orange },
	TSPunctSpecial = base.functions,
	TSRepeat = base.Repeat,
	TSString = base.String,
	TSStringRegex = { fg = c.green },
	TSStringEscape = { fg = c.purple },
	TSSymbol = { fg = c.blue },
	TSType = base.Typedef,
	TSTypeDefinition = base.typedef,
	TSTypeBuiltin = { fg = c.yellow },
	TSVariable = { fg = c.bright_yellow },
	TSVariableBuiltin = { fg = c.orange },

	TSTag = base.Tag,
	TSTagDelimiter = base.Delimiter,
	TSText = base.Normal,
	TSEmphasis = { italic = true },
	TSUnderline = { underline = true },
	TSStrike = { strikethrough = true },
	TSTitle = base.Title,
	TSLiteral = { fg = c.green },
	TSURI = { fg = c.blue, underline = true },
}

return theme

-- vi:nowrap
