local c = require("gruvboy.colors")
local base = require("gruvboy.base")

local theme = {
	TSAnnotation = { fg = c.blue },
	TSCharacter = base.Character,
	TSComment = base.Comment,
	TSConditional = base.Conditional,
	TSConstMacro = base.Macro,
	TSField = { fg = c.blue },
	TSFunction = base.Function,
	TSFuncBuiltin = { fg = c.aqua },
	TSInclude = base.Include,
	TSKeyword = base.Keyword,
	TSKeywordFunction = base.Keyword,
	TSMethod = { fg = c.aqua },
	TSNamespace = { fg = c.gray },
	TSNone = { fg = c.bg4 },
	TSOperator = base.Operator,
	TSParameter = { fg = c.blue },
	TSParameterReference = { fg = c.blue },
	TSProperty = { fg = c.blue },
	TSRepeat = base.Repeat,
	TSString = base.String,
	TSStringRegex = { fg = c.green },
	TSStringEscape = { fg = c.purple },
	TSType = base.Typedef,
	TSTypeDefinition = base.typedef,

	["@constructor"] = { fg = c.orange },
	["@constant"] = base.Constant,
	["@float"] = base.Float,
	["@number"] = base.Number,
	["@attribute"] = { fg = c.aqua },
	["@variable"] = { fg = c.bright_yellow },
	["@variable.builtin"] = { fg = c.orange },
	["@variable.global"] = { fg = c.bright_yellow, bold = true },
	["@boolean"] = base.Boolean,
	["@constant.builtin"] = { fg = c.purple },
	["@constant.macro"] = base.Macro,
	["@error"] = base.Error,
	["@exception"] = base.Exception,
	["@funtion.macro"] = base.Macro,
	["@include"] = base.Include,
	["@label"] = base.Label,
	["@operator"] = base.Operator,
	["@parameter"] = { fg = c.blue },
	["@punctuation.delimiter"] = base.Delimiter,
	["@punctuation.bracket"] = { fg = c.orange },
	["@punctuation.special"] = base.functions,
	["@symbol"] = { fg = c.blue },
	["@type"] = base.Typedef,
	["@type.builtin"] = { fg = c.yellow },
	["@tag"] = base.Tag,
	["@tag.delimiter"] = base.Delimiter,
	["@text"] = base.Normal,
	["@text.reference"] = { fg = c.blue },
	["@text.emphasis"] = base.Italic,
	["@text.underline"] = base.Underlined,
	["@text.title"] = base.Title,
	["@text.strong"] = { fg = c.fg1, bold = true },
	["@text.literal"] = { fg = c.green },
	["@text.uri"] = { fg = c.blue, underline = true },
}

return theme

-- vi:nowrap
