local lush = require("lush")
local c = require("gruvbox.colors.dark")

local theme = lush(function()
    return {
        Comment({ bg = c.bg0, fg = c.bg4, gui = "italic" }),
        ColorColumn({ bg = c.bg0, fg = c.bg1 }),
        Conceal({ fg = c.bright_blue }),
        Cursor({ gui = "reverse" }),
        lCursor({ gui = "reverse" }),
        CursorIM({ gui = "reverse" }),
        CursorColumn({ bg = c.bg1 }),
        CursorLine({ bg = c.bg1 }),
        Directory({ fg = c.bright_green, gui = "bold" }),
        DiffAdd({ fg = c.bright_green }),
        DiffChange({ fg = c.bright_aqua, gui = "reverse" }),
        DiffDelete({ fg = c.bright_red, gui = "reverse" }),
        DiffText({ fg = c.bright_yellow, gui = "reverse" }),
        EndOfBuffer({ fg = c.bg2 }),
        TermCursor({ gui = "reverse" }),
        TermCursorNC({ fg = c.bg1, bg = c.fg1 }),
        ErrorMsg({ fg = c.bg0, bg = c.bright_red }),
        VertSplit({ bg = c.bg0, fg = c.bg0 }),
        Folded({ fg = c.bg4, bg = c.bg1, gui = "italic" }),
        FoldColumn({ fg = c.bg4, bg = c.bg1 }),
        SignColumn({ fg = c.fg1 }),
        IncSearch({ fg = c.bright_yellow, gui = "reverse" }),
        Substitute({ fg = c.bright_yellow, gui = "reverse" }),
        LineNr({ fg = c.gray }),
        CursorLineNr({ fg = c.yellow }),
        MatchParen({ bg = c.bg2, gui = "underline" }),
        ModeMsg({ fg = c.fg1 }),
        MsgArea({ fg = c.fg1 }),
        MsgSeparator({ fg = c.fg1 }),
        MoreMsg({ fg = c.yellow }),
        NonText({ fg = c.bg2 }),
        Normal({ fg = c.fg1 }),
        NormalFloat({ fg = c.fg1, bg = c.bg2 }),
        NormalNC({ fg = c.fg1 }),
        Pmenu({ fg = c.fg1, bg = c.bg2 }),
        PmenuSel({ fg = c.bg2, bg = c.bright_blue, gui = "bold" }),
        PmenuSbar({ bg = c.bg2 }),
        PmenuThumb({ bg = c.bg3 }),
        Question({ fg = c.bright_orange, gui = "bold" }),
        QuickFixLine({ fg = c.bright_yellow, gui = "reverse" }),
        Search({ fg = c.bright_yellow, gui = "reverse" }),
        SpecialKey({ fg = c.bg4 }),
        SpellBad({ fg = c.fg0, gui = "underline", sp = c.red }),
        SpellCap({ fg = c.fg0, gui = "underline", sp = c.yellow }),
        SpellLocal({ fg = c.fg0, gui = "underline", sp = c.green }),
        SpellRare({ fg = c.fg0, gui = "underline", sp = c.blue }),
        TabLine({ bg = c.bg1, fg = c.fg0 }),
        TabLineFill({ fg = c.fg0 }),
        TabLineSel({ bg = c.bg1, fg = c.yellow }),
        Title({ fg = c.aqua, gui = "bold" }),
        Visual({ bg = c.bg3 }),
        VisualNOS({ gui = "reverse" }),
        WarningMsg({ fg = c.red }),
        Whitespace({ bg = c.bg0, fg = c.bg4, gui = "italic" }),
        WildMenu({ fg = c.bright_blue, bg = c.bg2, gui = "bold" }),

        Constant({ fg = c.purple }),
        String({ fg = c.green }),
        Character({ fg = c.purple }),
        Number({ fg = c.purple }),
        Boolean({ fg = c.purple }),
        Float({ fg = c.purple }),

        Identifier({ fg = c.blue }),
        Function({ fg = c.green, gui='bold' }),

        Statement({ fg = c.red }),
        Conditional({ fg = c.red }),
        Repeat({ fg = c.red }),
        Label({ fg = c.red }),
        Operator({ fg = c.aqua }),
        Keyword({ fg = c.red }),
        Exception({ fg = c.red }),

        PreProc({ fg = c.aqua }),
        Include({ fg = c.aqua }),
        Define({ fg = c.aqua }),
        Macro({ fg = c.aqua }),
        PreCondit({ fg = c.aqua }),

        Type({ fg = c.yellow }),
        StorageClass({ fg = c.orange }),
        Structure({ fg = c.aqua }),
        Typedef({ fg = c.yellow }),

        Special({ fg = c.orange }),
        SpecialChar({ fg = c.purple }),
        Tag({ fg = c.red }),
        Delimiter({ fg = c.orange }),
        SpecialComment({ fg = c.red }),
        Debug({ fg = c.red }),

        Underlined({ gui = "underline" }),
        Bold({ gui = "bold" }),
        Italic({ gui = "italic" }),

        Ignore({ fg = c.fg0 }),
        Error({ fg = c.bright_yellow }),
        Todo({ fg = c.fg3, gui = "bold,italic,reverse" }),
    }
end)

return theme

-- vi:nowrap
